name: CI

on: 
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Clean build artifacts
        run: python -c "import shutil; import os; [shutil.rmtree(p) for p in ['build', 'dist', *[d for d in os.listdir('.') if d.endswith('.egg-info')]] if os.path.exists(p)]"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -c "import os; os.path.exists('requirements.txt') and __import__('subprocess').run(['pip', 'install', '-r', 'requirements.txt'])"
          
      - name: Quality checks
        run: |
          python -c "import os, sys; main_exists = os.path.exists('main.py'); sys.exit(0 if not main_exists else 0 if os.path.getsize('main.py') < 1024 and 'def main' in open('main.py').read() else 1)"
