name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate tag version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          grep "version=\"$TAG\"" setup.py || (echo "Version mismatch between tag and setup.py" && exit 1)
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install build tools and minifier
        run: |
          python -m pip install --upgrade pip
          pip install build python-minifier
      
      - name: Minify Python source code
        run: |
          # Exemple : minifier le fichier go.py
          if [ -f "go.py" ]; then
            echo "Minification de go.py..."
            python -m python_minifier go.py > go.min.py && mv go.min.py go.py
          else
            echo "go.py non trouvé, minification ignorée."
          fi
      
      - name: Verify clean directory
        run: |
          if [ -d "dist" ] || [ -d "build" ] || ls *.egg-info 1> /dev/null 2>&1; then
            echo "Build directories should not exist"
            exit 1
          fi
      
      - name: Build package
        run: python -m build
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: false
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
